version: "3.8"
services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_USER: springuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: notes-ai
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 3303:3306
    volumes:
      - ./mysql-data:/var/lib/mysql    
    networks:
      springboot-mysql-net:

  spring-app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:  
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/notes-ai
      - spring.datasource.username=springuser
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: