spring:
    application:
        name: Demo AI Notes Application
        version: 1.0.0
    jpa:
        hibernate:
            ddl-auto: create
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3303/notes-ai
        username: springuser
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver

app:
  cors:
    allowed-origins: http://localhost:8080