spring:
    application:
        name: Demo AI Notes Application
        version: 1.0.0
    jpa:
        hibernate:
            ddl-auto: create
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:localhost}/${MYSQL_DATABASE:localhost}
        username: ${MYSQL_USER:localhost}
        password: ${MYSQL_PASSWORD:localhost}
        driver-class-name: com.mysql.cj.jdbc.Driver

app:
  cors:
    allowed-origins: http://localhost:8080